title: Ny New Blog
author: jacobinho86
email: jacobinho86@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first attempt to create a github page
#theme
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
